### ISSUE TITLE
Localizar la aplicación

### ISSUE THREAD

**Issue by rarguello** [AyudaEcuador/Ushahidi_Android#1]
Poner la aplicación en castellano.

**Comment by ovnicraft** [comment]
Avanzando https://www.transifex.com/ushahidi/ush_Android/language/es_419/

**Comment by ovnicraft** [comment]
Se puede probar la traducción @codeadict ?

**Comment by pablolopezmera** [comment]
Ya puse la traducción en la app, no tiene problemas.

**Comment by ovnicraft** [comment]
@pablolopezmera el archivo de traduccion se incluyo en el repo ?

**Comment by pablolopezmera** [comment]
@ovnicraft El strings_es.xml si.
