### ISSUE TITLE
Cambiar la imagen de la portada

### ISSUE THREAD

**Issue by rarguello** [AyudaEcuador/Ushahidi_Android#3]
Buscar una imagen mejor.

**Comment by pablolopezmera** [comment]
Pedí varias imágenes de la aplicación. En cuanto alguien de diseño me envíe lo pongo. Me gustaría saber si alguien está trabajando en eso. Caso contrario busco alguien.

**Comment by pablolopezmera** [comment]
Se aplicaron las imágenes de ayuda ecuador.
